# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.setFixedSize(1061, 754)
        Form.setAutoFillBackground(False)
        self.groupBox_account = QtWidgets.QGroupBox(Form)
        self.groupBox_account.setGeometry(QtCore.QRect(20, 20, 351, 101))
        self.groupBox_account.setObjectName("groupBox_account")
        self.label_Id = QtWidgets.QLabel(self.groupBox_account)
        self.label_Id.setGeometry(QtCore.QRect(20, 20, 58, 31))
        self.label_Id.setObjectName("label_Id")
        self.label_Pw = QtWidgets.QLabel(self.groupBox_account)
        self.label_Pw.setGeometry(QtCore.QRect(20, 60, 58, 21))
        self.label_Pw.setObjectName("label_Pw")
        self.lineEdit_Id = QtWidgets.QLineEdit(self.groupBox_account)
        self.lineEdit_Id.setGeometry(QtCore.QRect(70, 20, 151, 31))
        self.lineEdit_Id.setObjectName("lineEdit_Id")
        self.lineEdit_Pw = QtWidgets.QLineEdit(self.groupBox_account)
        self.lineEdit_Pw.setGeometry(QtCore.QRect(70, 56, 151, 31))
        self.lineEdit_Pw.setObjectName("lineEdit_Pw")
        self.lineEdit_Pw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pushButton_Signout = QtWidgets.QPushButton(self.groupBox_account)
        self.pushButton_Signout.setGeometry(QtCore.QRect(250, 70, 93, 28))
        self.pushButton_Signout.setObjectName("pushButton_Signout")
        self.pushButton_Login = QtWidgets.QPushButton(self.groupBox_account)
        self.pushButton_Login.setGeometry(QtCore.QRect(250, 10, 93, 28))
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.pushButton_Monitor = QtWidgets.QPushButton(self.groupBox_account)
        self.pushButton_Monitor.setGeometry(QtCore.QRect(250, 40, 93, 28))
        self.pushButton_Monitor.setObjectName("pushButton_Monitor")
        self.groupBox_Log = QtWidgets.QGroupBox(Form)
        self.groupBox_Log.setGeometry(QtCore.QRect(20, 550, 1031, 201))
        self.groupBox_Log.setObjectName("groupBox_Log")
        self.label_Status_Api = QtWidgets.QLabel(self.groupBox_Log)
        self.label_Status_Api.setGeometry(QtCore.QRect(20, 160, 58, 41))
        self.label_Status_Api.setObjectName("label_Status_Api")
        self.radioButton_Status_Api = QtWidgets.QRadioButton(self.groupBox_Log)
        self.radioButton_Status_Api.setEnabled(False)
        self.radioButton_Status_Api.setGeometry(QtCore.QRect(80, 170, 21, 21))
        self.radioButton_Status_Api.setTabletTracking(False)
        self.radioButton_Status_Api.setText("")
        self.radioButton_Status_Api.setObjectName("radioButton_Status_Api")
        self.textEdit_Log = QtWidgets.QTextEdit(self.groupBox_Log)
        self.textEdit_Log.setGeometry(QtCore.QRect(10, 20, 1011, 141))
        self.textEdit_Log.setObjectName("textEdit_Log")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 130, 1031, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.tableView_Stocks = QtWidgets.QTableView(self.widget)
        self.tableView_Stocks.setGeometry(QtCore.QRect(0, 0, 1021, 391))
        self.tableView_Stocks.setObjectName("tableView_Stocks")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableView_Futures = QtWidgets.QTableView(self.tab_2)
        self.tableView_Futures.setGeometry(QtCore.QRect(0, 0, 1021, 391))
        self.tableView_Futures.setObjectName("tableView_Futures")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableView_SeaFutures = QtWidgets.QTableView(self.tab_5)
        self.tableView_SeaFutures.setGeometry(QtCore.QRect(0, 0, 1021, 391))
        self.tableView_SeaFutures.setObjectName("tableView_SeaFutures")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView_StocksList = QtWidgets.QTableView(self.tab)
        self.tableView_StocksList.setGeometry(QtCore.QRect(0, 0, 1021, 391))
        self.tableView_StocksList.setObjectName("tableView_StocksList")
        self.tabWidget.addTab(self.tab, "")
        self.pushButton_LoadStocks = QtWidgets.QPushButton(Form)
        self.pushButton_LoadStocks.setGeometry(QtCore.QRect(400, 30, 93, 28))
        self.pushButton_LoadStocks.setObjectName("pushButton_LoadStocks")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_account.setTitle(_translate("Form", "群益帳戶"))
        self.label_Id.setText(_translate("Form", "帳號："))
        self.label_Pw.setText(_translate("Form", "密碼："))
        self.pushButton_Signout.setText(_translate("Form", "登出"))
        self.pushButton_Login.setText(_translate("Form", "登入"))
        self.pushButton_Monitor.setText(_translate("Form", "監控"))
        self.groupBox_Log.setTitle(_translate("Form", "Log"))
        self.label_Status_Api.setText(_translate("Form", "群益API"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Form", "股票"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "期貨"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "海期"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "商品選單"))
        self.pushButton_LoadStocks.setText(_translate("Form", "讀取商品"))

